version: '3.9'
services:
  rabbitmq:
    image: blankhang/rabbitmq:3.12-management
    environment:
      #- default user/pwd is blankhang/quest
      # - RABBITMQ_DEFAULT_USER=admin
      # - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_ERLANG_COOKIE=secret_cookie
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints: [node.role == worker]
    networks:
      - rabbitmq-cluster
    ports:
      - "15672:15672"
      - "5672:5672"
networks:
  rabbitmq-cluster:
    driver: overlay
