version: '3.7'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    restart: always
    # privileged: true
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    environment:
      TZ: "Asia/Shanghai"
      ACCEPT_EULA: "Y"
      SA_PASSWORD: $DB_PASSWORD
      MSSQL_PID: "Developer"
      MSSQL_COLLATION: "Chinese_PRC_CI_AS"
    volumes:
      - "./data:/var/opt/mssql/data"
      - "./log:/var/opt/mssql/log"
      - "./secrets:/var/opt/mssql/secrets"
    ports:
      - 1433:1433

# docker run
# -e 'ACCEPT_EULA=Y'
# -e 'MSSQL_SA_PASSWORD=<YourStrong!Passw0rd>'
# -p 1433:1433
# -v <host directory>/data:/var/opt/mssql/data
# -v <host directory>/log:/var/opt/mssql/log
# -v <host directory>/secrets:/var/opt/mssql/secrets
# -d mcr.microsoft.com/mssql/server:2017-latest