version: '3.7'

services:

  redis:
    image: redis:6
    restart: always
    container_name: redis6
    hostname: redis
    healthcheck:
      test: curl -s https://localhost:6379 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 5s
      timeout: 10s
      retries: 3
    volumes:
      - '/docker/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf'
#      - 'redis_data:/data'
#    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

#volumes:
#  redis_data:

# redis default conf
# #http://download.redis.io/redis-stable/redis.conf