version: '3.7'

services:

  redis:
    image: redis:5
    restart: always
    container_name: redis
    hostname: redis
    volumes:
      - '/docker/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf'
      - '/docker/redis/data:/data'
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "59394:59394"

#  redis-commander:
#    image: rediscommander/redis-commander:latest
#    container_name: redis-commander
#    environment:
#     - REDIS_HOST=redis
#     - REDIS_PORT=59394
#     - REDIS_PASSWORD=123456
#    ports:
#    - "59395:8081"


#volumes:
#  redis_data:

# redis default conf
# #http://download.redis.io/redis-stable/redis.conf