services:
  es-node1:
    image: blankhang/elasticsearch:${ELK_VERSION}
    restart: always
    ports:
      - "19201:9200"
    deploy:
      placement:
        constraints: [node.hostname == xhc-wh-1]
      resources:
        limits:
          memory: 6G
      update_config:
        parallelism: 1
        delay: 90s
        order: stop-first
        failure_action: pause
    environment:
      - reindex.remote.whitelist=47.253.111.89:19201,120.24.64.42:19201
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - path.repo=/usr/share/elasticsearch/backup
      - node.name=es-node1
      - cluster.name=es-cluster
      - network.publish_host=es-node1
      - discovery.seed_hosts=es-node2,es-node3
      # 仅在初始化部署时需要，一旦部署成功则应该注释掉下面这行重新部署应用
      - cluster.initial_master_nodes=es-node1,es-node2,es-node3
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.keystore.path=/usr/share/elasticsearch/config/certs/elastic-certificates.p12
      - xpack.security.transport.ssl.truststore.path=/usr/share/elasticsearch/config/certs/elastic-certificates.p12
    configs:
      - source: elastic-certificates_p12
        target: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
    volumes:
      - /docker/es/es-prod-stack/data-elasticsearch-node1:/usr/share/elasticsearch/data
      - /docker/es/es-prod-stack/es-backup:/usr/share/elasticsearch/backup
    networks:
      - es-net

  es-node2:
    image: blankhang/elasticsearch:${ELK_VERSION}
    restart: always
    ports:
      - "19202:9200"
    deploy:
      placement:
        constraints: [node.hostname == xhc-wh-2]
      resources:
        limits:
          memory: 6G
      update_config:
        parallelism: 1
        delay: 90s
        order: stop-first
        failure_action: pause
    environment:
      - reindex.remote.whitelist=47.253.111.89:19201,120.24.64.42:19201
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - path.repo=/usr/share/elasticsearch/backup
      - node.name=es-node2
      - cluster.name=es-cluster
      - network.publish_host=es-node2
      - discovery.seed_hosts=es-node1,es-node3
      - cluster.initial_master_nodes=es-node1,es-node2,es-node3
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.keystore.path=/usr/share/elasticsearch/config/certs/elastic-certificates.p12
      - xpack.security.transport.ssl.truststore.path=/usr/share/elasticsearch/config/certs/elastic-certificates.p12
    configs:
      - source: elastic-certificates_p12
        target: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
    volumes:
      - /docker/es/es-prod-stack/data-elasticsearch-node2:/usr/share/elasticsearch/data
      - /docker/es/es-prod-stack/es-backup:/usr/share/elasticsearch/backup
    networks:
      - es-net

  es-node3:
    image: blankhang/elasticsearch:${ELK_VERSION}
    restart: always
    ports:
      - "19203:9200"
    deploy:
      placement:
        constraints: [node.hostname == xhc-wh-3]
      resources:
        limits:
          memory: 6G
      update_config:
        parallelism: 1
        delay: 90s
        order: stop-first
        failure_action: pause
    environment:
      - reindex.remote.whitelist=47.253.111.89:19201,120.24.64.42:19201
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - path.repo=/usr/share/elasticsearch/backup
      - node.name=es-node3
      - cluster.name=es-cluster
      - network.publish_host=es-node3
      - discovery.seed_hosts=es-node1,es-node2
      - cluster.initial_master_nodes=es-node1,es-node2,es-node3
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.keystore.path=/usr/share/elasticsearch/config/certs/elastic-certificates.p12
      - xpack.security.transport.ssl.truststore.path=/usr/share/elasticsearch/config/certs/elastic-certificates.p12
    configs:
      - source: elastic-certificates_p12
        target: /usr/share/elasticsearch/config/certs/elastic-certificates.p12

    volumes:
      - /docker/es/es-prod-stack/data-elasticsearch-node3:/usr/share/elasticsearch/data
      - /docker/es/es-prod-stack/es-backup:/usr/share/elasticsearch/backup
    networks:
      - es-net

  kibana:
    image: kibana:${ELK_VERSION}
    restart: always
    ports:
      - "15601:5601"
    deploy:
      placement:
        constraints: [node.hostname == xhc-wh-1]
      resources:
        limits:
          memory: 1G
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://es-node1:9200
#      - ELASTICSEARCH_HOSTS=http://haproxy:19200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=${XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY}
      - XPACK_REPORTING_ENCRYPTIONKEY=${XPACK_REPORTING_ENCRYPTIONKEY}
      - XPACK_SECURITY_ENCRYPTIONKEY=${XPACK_SECURITY_ENCRYPTIONKEY}
      - XPACK_REPORTING_KIBANASERVER_HOSTNAME=localhost
      - I18N_LOCALE=zh-CN
      - DATEFORMAT_TZ=Asia/Shanghai
    volumes:
      - /docker/es/es-prod-stack/data-kibana:/usr/share/kibana/data
    networks:
      - es-net

networks:
  es-net:
    driver: overlay

configs:
  elastic-certificates_p12:
    file: ./conf/elastic-certificates_p12
