FROM blankhang/alpine324
LABEL maintainer="blankhang <blankhang@gmail.com>" \
      version="1.0" \
      description="alpine3.24 with openjdk21 and chinese language and CST GMT+8 timezone support"
RUN apk add --no-cache openjdk21
