version: '3.7'
services:

  nginx:
    image: nginx
    container_name: nginx
    #privileged: true
    restart: always
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 3s
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /app:/app
      - /docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /docker/nginx/conf.d:/etc/nginx/conf.d
      - /docker/nginx/ssl:/etc/nginx/ssl
      - /docker/nginx/log:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - default
    command: [nginx, '-g', 'daemon off;']