# 如果是动态模块需要使用 load_module 的方式来加载它
load_module /docker/nginx/ip/nginx-geoip2-nginx-1.31.1-linux-amd64.so
load_module /docker/nginx/ip/nginx-ip2region-nginx-1.31.1-linux-amd64.so



user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;

events {
    worker_connections 65535;
    multi_accept on;
    use epoll;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  mainOld  '$remote_addr $ip2region - $remote_user [$time_local] "$request" '
                       '$status $body_bytes_sent "$http_referer" '
                       '"$http_user_agent" "$http_x_forwarded_for"';


    log_format main escape=json '{'
                    '"time": "$time_local", '
                    '"remote_addr": "$remote_addr", '
                    '"region": "$ip2region", '
                    '"country_code": "$geoip2_country_code", '
                    '"country_name": "$geoip2_country_name", '
                    '"method": "$request_method", '
                    '"uri": "$request_uri", '
                    '"status": "$status", '
                    '"body_bytes_sent": "$body_bytes_sent", '
                    '"referer": "$http_referer", '
                    '"user_agent": "$http_user_agent", '
                    '"http_x_forwarded_for": "$http_x_forwarded_for"'
    '}';

#     log_format main2 escape=json '{'
#                     '"time": "$time_local", '
#                     '"remote_addr": "$remote_addr", '
#                     '"country_code": "$geoip2_country_code", '
#                     '"country_name": "$geoip2_country_name", '
#                     '"city_name": "$geoip2_city_name", '
#                     '"method": "$request_method", '
#                     '"uri": "$request_uri", '
#                     '"status": "$status", '
#                     '"body_bytes_sent": "$body_bytes_sent", '
#                     '"referer": "$http_referer", '
#                     '"user_agent": "$http_user_agent", '
#                     '"http_x_forwarded_for": "$http_x_forwarded_for"'
#     '}';

    # ip2region 保留注释
    # set xdb file path
     ip2region_db /docker/nginx/ip/ip2region_v4.xdb;
    # ip2region_db ip2region.xdb vectorIndex;
    # ip2region_db ip2region.xdb file;
    # ip2region_db ip2region.xdb content;

    #geoip_country /usr/share/GeoIP/GeoIP.dat;
    #geoip_city /docker/nginx/maxmind.dat;


    # GeoIP2 配置
    geoip2 /docker/nginx/ip/GeoLite2-City.mmdb {
        auto_reload 6h;
        $geoip2_country_code country iso_code;
        $geoip2_country_name country names en;
        $geoip2_city_name city names en;
    }

    access_log  /var/log/nginx/access.log  main buffer=32k flush=5s;

    sendfile        on;
    tcp_nopush      on;
    gzip on;
    gzip_types application/json text/plain application/javascript;
    gzip_comp_level 5;
    gzip_min_length 1k;

    keepalive_timeout  65;

    types_hash_max_size 2048;

    proxy_headers_hash_max_size 1024;
    proxy_headers_hash_bucket_size 128;

    include /etc/nginx/conf.d/*.conf;
    include /docker/nginx/conf.d/*.conf;
}
