version: '3.7'
services:
  mysql:
    image: mysql:8
    hostname: mysql
    restart: always
    container_name: mysql8
    healthcheck:
      test: "mysqladmin ping -h localhost -P 3306 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD"
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      TZ: Asia/Shanghai
      #MYSQL_ALLOW_EMPTY_PASSWORD: 'Y'
      MYSQL_ROOT_PASSWORD: "bXnT5oJp79*nRoYfSYYo"
      MYSQL_DATABASE: "test"
      MYSQL_USER: "blankhang"
      MYSQL_PASSWORD: "6T5zXnFF&92W!9599#L4"
    volumes:
      - ./conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./data:/var/lib/mysql
      - ./log:/var/log/mysql
      # init sql
      #- ./mysql/sql/master:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    command:
      --default-authentication-plugin=mysql_native_password