version: '3.7'
services:
  mysql:
    image: mysql:8
    hostname: mysql
    restart: always
    container_name: mysql
    user: "999:999"
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 15s
      retries: 10
      interval: 5s
      start_period: 10s
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: "123456"
      #MYSQL_DATABASE: "test"
      #MYSQL_USER: "blank"
      #MYSQL_PASSWORD: "123456"
    volumes:
      - ./conf.d:/etc/mysql/conf.d
      - ./data:/var/lib/mysql
      - ./log:/var/log/mysql
      # init sql
      #- ./mysql/sql/master:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"