version: '3.8'

services:
  jenkins:
    # build:
    #  dockerfile: Dockerfile
    #  context: .
    image: blankhang/jenkins
    container_name: jenkins
    restart: always
    privileged: true
    user: root

    healthcheck:
      test: curl -s https://localhost:8080 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 1m
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          # Recommended to limit on low performance servers
          cpus: '0.90'
    ports:
      - '8080:8080'
    networks:
      - default
    volumes:
      - '/app:/app'
      - '/etc/localtime:/etc/localtime'
      - '/docker/jenkins/jenkins_home:/var/jenkins_home'
      - '/etc/localtime:/etc/localtime:ro'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '~/.ssh:/var/jenkins_home/.ssh'
      - '~/.m2:/root/.m2'