global:
  scrape_interval: 60s # Set the scrape interval to every 5 seconds. Default is every 1 minute.
  evaluation_interval: 60s # Evaluate rules every 15 seconds. The default is every 1 minute.
# scrape_timeout is set to the global default (10s).  
  external_labels:
    namespace: local

rule_files:
  - /etc/prometheus/recording-rules.yml
  - /etc/prometheus/alerting-rules.yml

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [ 'localhost:9090' ]
        labels:
          container: 'prometheus'

  - job_name: alertmanager
    static_configs:
      - targets: [ 'alertmanager:9093' ]
        labels:
          container: 'alertmanager'

  - job_name: node-exporter
    static_configs:
      - targets: 
        - '192.168.50.11:9100'
        - '192.168.50.12:9100'
        - '192.168.50.13:9100'
        - '192.168.50.14:9100'
        - '192.168.50.15:9100'

  - job_name: cadvisor
    static_configs:
      - targets:
        - '192.168.50.11:8080'
        - '192.168.50.12:8080'
        - '192.168.50.13:8080'
        - '192.168.50.14:8080'
        - '192.168.50.15:8080'

  - job_name: mysql-exporter
    static_configs: 
      - targets: [ '192.168.50.11:9104' ] 
        # labels: 
        #   instance: 'mysql-exporter'

  - job_name: redis-exporter
    # https://github.com/oliver006/redis_exporter/blob/master/README.md
    #redis grafana dashboard id 763
    static_configs:
      - targets: 
        - 'redis://192.168.50.11:6379'
    metrics_path: /scrape        
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.50.11:9121

  - job_name: minio
    # minio grafana dashboard id 13502
    # https://grafana.com/grafana/dashboards/13502-minio-dashboard/
    # see more
    # https://github.com/minio/minio/blob/master/docs/metrics/prometheus/README.md
    # MinIO deployments started with MINIO_PROMETHEUS_AUTH_TYPE set to "public" can omit the bearer_token field. 
    #bearer_token: TOKEN
    metrics_path: /minio/v2/metrics/cluster
    scrape_interval: 60s
    params:
      format: [ 'prometheus' ]    
    scheme: http
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets:
        - '192.168.50.11:9000'
        - '192.168.50.12:9000'
        - '192.168.50.13:9000'
        - '192.168.50.14:9000'

  - job_name: jenkins
    # https://grafana.com/grafana/dashboards/9964-jenkins-performance-and-health-overview/
    # dashboard id 9964
    # jenkins need install https://plugins.jenkins.io/prometheus/ first
    # http://<jenkinsIP>:<Port>/prometheus/
    metrics_path: /prometheus
    scheme: http
    static_configs:
      - targets:
        - '192.168.50.11:8888'

  - job_name: emqx
    # https://grafana.com/grafana/dashboards/17446-emqx/
    # dashboard id 17446
    metrics_path: /api/v5/prometheus/stats
    scrape_interval: 60s
    honor_labels: true
    static_configs:
      # EMQX IP address and port
      - targets: ['192.168.50.11:18083']

  #- job_name: nginx
  #nginx grafana dashboard id 9614
  

  - job_name: nacos
    # dashboard id 13221
    scrape_interval: 60s
    metrics_path: '/nacos/actuator/prometheus'
    static_configs:
      - targets: ['192.168.50.11:8848']
        labels:
          instance: nacos


  - job_name: springboot-wifi
    # dashboard id 4701
    scrape_interval: 60s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.50.2:9100']