version: '3.7'
services:
  speedtest-x:
    restart: always
    image: badapple9/speedtest-x
    container_name: speedtest-x
    environment:
      - TZ=Asia/Shanghai
      - MAX_LOG_COUNT=100
      - SAME_IP_MULTI_LOGS=TRUE
    ports:
      - "9001:80"
