version: "3.7"
services:

  haproxy:
    image: haproxy
    hostname: haproxy
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 1m
      restart_policy:
        condition: on-failure
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - 35671:35671 # RabbitMQ load balance AMQP port
      - 35672:35672 # RabbitMQ management ui http port
      - 35673:35673 # haproyx stats http port
    configs:
      - source: haproxy_cfg
        target: /usr/local/etc/haproxy/haproxy.cfg
    networks:
      - rabbitmq_rabbitmq-cluster

configs:
  haproxy_cfg:
    file: ./haproxy.cfg

networks:
  rabbitmq_rabbitmq-cluster:
#    driver: overlay
    external: true