version: '3.8'
services:
  mysql:
    image: mysql:8
    hostname: mysql
    restart: always
    container_name: mysql8
    # docker mysql error fix      | mbind: Operation not permitted
    # https://stackoverflow.com/questions/55559386/how-to-fix-mbind-operation-not-permitted-in-mysql-error-log
    cap_add:
      - SYS_NICE
    # security_opt:
    #   - seccomp:unconfined
    healthcheck:
      test: "mysqladmin ping -h localhost -P 3306 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD"
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      TZ: Asia/Shanghai
      #MYSQL_ALLOW_EMPTY_PASSWORD: 'Y'
      MYSQL_ROOT_PASSWORD: "bXnT5oJp79*nRoYfSYYo"
      MYSQL_DATABASE: "test"
      MYSQL_USER: "blankhang"
      MYSQL_PASSWORD: "6T5zXnFF&92W!9599#L4"
    volumes:
      - ./conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./data:/var/lib/mysql
      - ./log:/var/log/mysql
      # init sql
      #- ./mysql/sql/master:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    command:
      --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    entrypoint: bash -c "chown -R mysql:mysql /var/log/mysql && exec /entrypoint.sh mysqld"