version: "3.9"
services:
  minio1:
    hostname: minio1
    image: minio/minio
    environment:
      TZ: "Asia/Shanghai"
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "12345678"
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
      MINIO_PROMETHEUS_JOB_ID: "minio"
      MINIO_PROMETHEUS_URL: "192.168.50.11:9090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      placement:
        constraints:
          - 'node.hostname == vm-ubuntu-11'
    volumes:
      # need file directory /docker/docker-stack/minio/data1 exits on the host name vm-ubuntu-11
      - /docker/docker-stack/minio/data1:/data
    command: server --console-address ":9001" http://minio{1...4}/data
    networks:
      - minio-overlay-network
      # expose:
      # - "9000"
      # ports:
      # - "9001:9000"

  minio2:
    hostname: minio2
    image: minio/minio
    environment:
      TZ: "Asia/Shanghai"
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "12345678"
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
      MINIO_PROMETHEUS_JOB_ID: "minio"
      MINIO_PROMETHEUS_URL: "192.168.50.11:9090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      placement:
        constraints:
          - 'node.hostname == vm-ubuntu-12'
    volumes:
      # need file directory /docker/docker-stack/minio/data2 exits on the host name vm-ubuntu-12
      - /docker/docker-stack/minio/data2:/data
    command: server --console-address ":9001" http://minio{1...4}/data
    networks:
      - minio-overlay-network
      # ports:
      # - "9002:9000"

  minio3:
    hostname: minio3
    image: minio/minio
    environment:
      TZ: "Asia/Shanghai"
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "12345678"
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
      MINIO_PROMETHEUS_JOB_ID: "minio"
      MINIO_PROMETHEUS_URL: "192.168.50.11:9090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      placement:
        constraints:
          # need file directory /docker/docker-stack/minio/data3 exits on the host name vm-ubuntu-13
          - 'node.hostname == vm-ubuntu-13'
    volumes:
      - /docker/docker-stack/minio/data3:/data
    command: server --console-address ":9001" http://minio{1...4}/data
    networks:
      - minio-overlay-network
      # ports:
      # - "9003:9000"

  minio4:
    hostname: minio4
    image: minio/minio
    environment:
      TZ: "Asia/Shanghai"
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "12345678"
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
      MINIO_PROMETHEUS_JOB_ID: "minio"
      MINIO_PROMETHEUS_URL: "192.168.50.11:9090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      placement:
        constraints:
          - 'node.hostname == vm-ubuntu-14'
    volumes:
      # need file directory /docker/docker-stack/minio/data4 exits on the host name vm-ubuntu-14
      - /docker/docker-stack/minio/data4:/data
    command: server --console-address ":9001" http://minio{1...4}/data
    networks:
      - minio-overlay-network
      # ports:
      # - "9004:9000"

  nginx:
    image: nginx:1.25.0-alpine
    hostname: nginx
    environment:
      TZ: "Asia/Shanghai"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:9000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      placement:
        constraints:
          - 'node.hostname == vm-ubuntu-11'
    volumes:
      # need file /docker/docker-stack/minio/nginx.conf exits on the host name vm-ubuntu-14
      - /docker/docker-stack/minio/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - minio-overlay-network
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4

networks:
  minio-overlay-network:
    driver: overlay
