# Redis 主/从公共配置（密码、replicaof、replica-announce 由 redis-stack.yml 注入）
# replica-announce-ip/port：官方 Docker/NAT 下从库地址，见
# https://redis.io/docs/latest/operate/oss_and_stack/management/sentinel/#sentinel-docker-nat-and-possible-issues

bind 0.0.0.0
protected-mode yes
tcp-backlog 511
timeout 0
tcp-keepalive 300
daemonize no
supervised no
pidfile /var/run/redis.pid
loglevel notice
databases 16
always-show-logo no
set-proc-title yes

dir /data
appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec
no-appendfsync-on-rewrite no
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb

replica-serve-stale-data yes
replica-read-only yes

io-threads 7
io-threads-do-reads yes
