name: Docker Image Jenkins  CI
on:
  workflow_dispatch: #github页面手动触发
  push:
    tags:
      - "v*.*" # github 发布tag时触发自动构建
# on:
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

env:
  IMAGE: jenkins # 镜像
  IMAGE_NAME: blankhang/jenkins #这是您的镜像名
  
jobs:

  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3.5.3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker Login
      #if: github.event_name !='pull_request'
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: ./${{ env.IMAGE }}/build
        file: ./${{ env.IMAGE }}/build/Dockerfile
        platforms: linux/amd64,linux/arm/v7,linux/arm64
        #,linux/ppc64le,linux/s390x
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
        tags: ${{ env.IMAGE_NAME }}:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}