name: Docker Image Centos7 Openjdk CI
on:
  workflow_dispatch: #github页面手动触发
  push:
    tags:
      - "v*.*" # github 发布tag时触发自动构建
# on:
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

env:
  IMAGE: centos7
  IMAGE_NAME_OPENJDK8: blankhang/centos7:openjdk8 #这是您的镜像名
  IMAGE_NAME_OPENJDK11: blankhang/centos7:openjdk11 #这是您的镜像名
  IMAGE_NAME_OPENJDK17: blankhang/centos7:openjdk17 #这是您的镜像名

jobs:

  build:
    runs-on: ubuntu-22.04
    env:
      TZ: Asia/Shanghai
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3.5.3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker Login
      #if: github.event_name !='pull_request'
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build openjdk8 and push
      id: openjdk8_build
      uses: docker/build-push-action@v4
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: ./${{ env.IMAGE }}
        file: ./${{ env.IMAGE }}/openjdk8/Dockerfile
        platforms: linux/amd64,linux/arm64
        #,linux/ppc64le,linux/s390x
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
        tags: ${{ env.IMAGE_NAME_OPENJDK8 }}

    - name: Build openjdk11 and push
      id: openjdk11_build
      uses: docker/build-push-action@v4
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: ./${{ env.IMAGE }}
        file: ./${{ env.IMAGE }}/openjdk11/Dockerfile
        platforms: linux/amd64,linux/arm64
        #,linux/ppc64le,linux/s390x
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
        tags: ${{ env.IMAGE_NAME_OPENJDK11 }}

    - name: Build openjdk17 amd64 and push
      id: openjdk17_build
      uses: docker/build-push-action@v4
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: ./${{ env.IMAGE }}
        file: ./${{ env.IMAGE }}/openjdk17/Dockerfile
        platforms: linux/amd64
        #,linux/ppc64le,linux/s390x
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
        tags: ${{ env.IMAGE_NAME_OPENJDK17 }}

    - name: Build openjdk17 arm64 and push
      id: openjdk17_build
      uses: docker/build-push-action@v4
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: ./${{ env.IMAGE }}
        file: ./${{ env.IMAGE }}/openjdk17/Dockerfile-arm64v8
        platforms: linux/arm64
        #,linux/ppc64le,linux/s390x
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
        tags: ${{ env.IMAGE_NAME_OPENJDK17 }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}