name: Docker Image Jenkins CI
on:
  workflow_dispatch: # github页面手动触发
  push:
    tags:
      - "v*.*" # github 发布tag时触发自动构建

env:
  IMAGE: jenkins # 镜像
  IMAGE_jdk_17_NAME: blankhang/jenkins #这是您的镜像名
  IMAGE_JDK_21_NAME: blankhang/jenkins:lts-jdk21 #这是您的镜像名

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build openjdk-21 and push
        id: openjdk21_build
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./${{ env.IMAGE }}/build
          file: ./${{ env.IMAGE }}/build/android/jdk21.Dockerfile
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: ${{ env.IMAGE_JDK_21_NAME }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Login to AliDockerHub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}
          username: ${{ secrets.ALI_DOCKER_HUB_USN }}
          password: ${{ secrets.ALI_DOCKER_HUB_PWD }}

      - name: ReTag and push to AliDockerHub
        run: |
          docker pull ${{ env.IMAGE_JDK_21_NAME }}
          docker tag ${{ env.IMAGE_JDK_21_NAME }} ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}/blankhang/jenkins:lts-jdk21
          docker push ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}/blankhang/jenkins:lts-jdk21